### ISSUE TITLE
Improve Readability Overview Page (Part 1)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/magazine.joomla.org#15]
Hi everyone, 
I'd like to suggest to improve the readability of the blog by adding these changes:

Before:
![grafik](https://user-images.githubusercontent.com/828371/99816054-77f4b700-2b4b-11eb-8e2a-c67a84d45a27.png)

After:

![grafik](https://user-images.githubusercontent.com/828371/99815986-5d224280-2b4b-11eb-8693-8686b5f42c1c.png)

#eb .eb-mag .eb-mag-body {
    font-size: 18px;
    line-height: 135%;
}

#eb .eb-mag .eb-mag-grids__item {
    padding: 15px;
}

#eb .magazine-btn-more {
font-size: 18px;
border: none;
background: #46af3e;
color: #fff !important;
font-weight: normal;
}
Element {

}
#eb .eb-mag a {

    color: inherit;

}
#eb a:link {

    text-decoration: none;
        text-decoration-line: none;
        text-decoration-style: solid;
        text-decoration-color: currentcolor;
        text-decoration-thickness: auto;

}
a {

    color: #08c;
    text-decoration: none;
        text-decoration-line: none;
        text-decoration-style: solid;
        text-decoration-color: currentcolor;
        text-decoration-thickness: auto;

}
#eb .eb-mag-title {

    font-size: 18px;
    font-weight: bold;
    line-height: 130%;
    color: #2B3455 !important;
}

#eb .eb-mag-thumb {
    margin: 10px 0;
    max-height: 160px;
}

**Comment by conconnl** [comment]
@particthistle can you create a PR for the things the team agreed upon?
https://github.com/joomla/magazine.joomla.org/blob/master/www/templates/joomla/css/custom.css

**Comment by particthistle** [comment]
Similar to #16 some minor adjustments to @coolcat-creations suggestion. Not all the changes listed are shown in the code below. See following PR for all changes in one place.

- Font size 16px instead of 18px
- Continue Reading buttons aligned extending #24 (will be in PR)
- Suggested formatting additionally applied to the issues page instead of just the home page.
- Buttons blue instead of green to match existing magazine template flow in other sections
- Styled in #16 are also applied to some items in the screen shot below.
- Also changed images from cover to contain so the article thumbnails now show as full images vs cropping.
- Changed mobile columns from 3 to 1 so now mobile readers get a cleaner view of issues in one column.

`/* EasyBlog Article styles
- proposed in https://github.com/joomla/magazine.joomla.org/issues/15 by @coolcat-creations
- Tweaked by @particthistle April 2021
*/
#eb .eb-mag .eb-mag-body, #eb .eb-blog-grid__body {
  font-size: 16px;
  line-height: 135%;
}
#eb .eb-mag .eb-mag-grids__item, #eb .eb-blog-grid__item {
  padding: 15px;
}
#eb .magazine-btn-more, #eb .eb-post-more .btn {
  font-size: 16px;
  border: none;
  background: #1e88e5 !important;
  color: #fff !important;
  font-weight: normal;
	width: 100%;
}
#eb .magazine-btn-more:hover, #eb .eb-post-more .btn:hover {
  background-color: #1773c4 !important;
}
#eb .eb-mag a {
  color: inherit;
}
#eb a:link {
  text-decoration: none;
  text-decoration-line: none;
  text-decoration-style: solid;
  text-decoration-color: currentcolor;
  text-decoration-thickness: auto;
}
a {
  color: #08c;
  text-decoration: none;
  text-decoration-line: none;
  text-decoration-style: solid;
  text-decoration-color: currentcolor;
  text-decoration-thickness: auto;
}
#eb .eb-mag-title, #eb .eb-blog-grid__title {
  font-size: 18px;
  font-weight: bold;
  line-height: 130%;
  color: #2B3455 !important;
}
#eb .eb-mag-thumb {
  margin: 10px 0;
  max-height: 160px;
}`

![image](https://user-images.githubusercontent.com/5515866/113383421-9d35e380-93cf-11eb-95d5-fa2cc759e0ac.png)

Mobile before:
![image](https://user-images.githubusercontent.com/5515866/113383498-c9516480-93cf-11eb-8978-4a494b095d57.png)


Mobile after: 
![image](https://user-images.githubusercontent.com/5515866/113383465-b8085800-93cf-11eb-9bf9-73c1b3443e10.png)

**Comment by particthistle** [comment]
Please add further comments now to #25.
