### ISSUE TITLE
Mime type error in component EasyBlog

### ISSUE THREAD

**Issue by conconnl** [joomla/magazine.joomla.org#38]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/11913918/133313192-062bba93-b371-4858-9de1-1e4eae0553a6.png">

@imarklee please solve in extension, it's a conflict in delivered mime type compared to what is logical for CSS

**Comment by imarklee** [comment]
Hm, this is odd because the file https://magazine.joomla.org/media/com_easyblog/vendors/mmenu/mmenu.css is generating a 404.

Can you download the file below, extract it and upload it into /media/com_easyblog/vendors/mmenu/

[mmenu.zip](https://github.com/joomla/magazine.joomla.org/files/7165968/mmenu.zip)

**Comment by conconnl** [comment]
I don't see the Vendors map at.
<img width="168" alt="image" src="https://user-images.githubusercontent.com/11913918/133688236-92a60c86-7798-4ce8-b99a-dc75e054c8ac.png">

Do we miss more?

**Comment by imarklee** [comment]
Yeah, you need to create the folder vendors/mmenu

**Comment by conconnl** [comment]
> Yeah, you need to create the folder vendors/mmenu

I understand, because the folder wasn't there I was afraid we missed more files then only the mmenu.
